export const SET_USER = 'SET_USER';
export const CLEAR_USER = "CLEAR_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
// export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

// export const PRESSED_HELLO_BUTTON = "PRESSED_HELLO_BUTTON"
